spring:
  datasource:
    url: jdbc:mysql://mysql:3306/blog_db?serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: redis
  rabbitmq:
    addresses: rabbitmq
    port: 5672
  profiles:
    active: prod

easy:
  elastic-search:
    addr: elastic-search
    port: 9200
