server:
  port: 1000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.169.2:3306/blog_db?serverTimezone=UTC
    username: root
    password: Kz99596589
  redis:
    host: 192.168.169.2
  rabbitmq:
    addresses: 192.168.169.2
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated #开启发送端确认
    publisher-returns: true # 开启发送端消息抵达队列的确认
    template:
      mandatory: true #只要抵达队列,以异步的方式优先回调returnConfirm
    listener:
      simple:
        acknowledge-mode: manual #手动确认消息


easy:
  thread:
    core-size: 50
    max-size: 200
    keep-alive-time: 10
  PermissionItem:
    article-permission:
      article-self: 可操作自己
      article-visible-to-others: 可见他人
      article-operation-to-others: 可操作他人
    tag-permission:
      tag-self: 可操作自己
      tag-operation-to-others: 可操作他人
    comment-permission:
      comment-self: 可操作自己
      comment-visible-to-others: 可见他人
      comment-operation-to-others: 可操作他人
    setting-permission:
      setting-normal: 常规设置
      setting-comment: 评论设置
      setting-smtp: SMTP设置
      setting-attachment : 附件设置




  jwt:
    header: Authorization
    base64-secret: sanbayan
    token-validity-in-seconds: 14400000


# Logger Config
logging:
  level:
    com.freedy.backend: debug

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
